### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ReubenMenezes**
Fixed typo in README and added favicon

### CODE REVIEW

**Comment by teotwaki** [comment]
@ReubenMenezes Thanks for the contribution!

Can I ask you to put the image in `/assets/images` instead of `.images`? `.images` is only used for images shown in GitHub (the screenshots in the readme), and is not copied to the final docker file. You should also update the path in the files to `href="/assets/images/liro.webp"`

What's the motivation for using an Android-style favicon link?

**Comment by ReubenMenezes** [comment]
Sure thing! I'll make a new pull request with it. I'm sorry but I don't understand what you mean by Android-style favicon link

**Comment by teotwaki** [comment]
@ReubenMenezes No need to close the PR and delete the branch, you can always just push more commits when you get feedback.

Android style is "shortcut icon", and a specific size. Standard web is only "icon".

**Comment by ReubenMenezes** [comment]
I see, apologies. 
There was no inspiration for the Android icon. I simply used  `link:favicon` ( an emmet feature ) Is there any reason not to use it or is it fine?

**Pull request closed without merging**
